(()=>{'use strict';const data=window.PORTFOLIO,main=document.getElementById('main'),list=document.getElementById('work-list'),dialog=document.getElementById('project-dialog'),lightbox=document.getElementById('lightbox'),reduced=matchMedia('(prefers-reduced-motion: reduce)');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const highlight=s=>esc(s).replace(/AI 视觉创作|发布与复盘|用户兴趣|人文与情感内容|选题|文案/g,m=>`<span class="hover-word">${m}</span>`);const person=data.person;document.querySelector('.about-copy>.eyebrow').textContent=`你好，我是${person.name}。`;document.querySelector('.about-intro').innerHTML=highlight(person.intro)+'<br>'+highlight(person.description);document.querySelector('.identity').innerHTML=[['姓名',person.name],['学历',person.education],['城市',person.city],['求职方向',person.role]].map(([a,b])=>`<div><dt>${esc(a)}</dt><dd><span class="hover-word">${esc(b)}</span></dd></div>`).join('');const abilities=document.querySelector('.abilities');document.querySelector('.about-layout').after(abilities);abilities.setAttribute('aria-label','个人能力');abilities.innerHTML=person.skills.map(([a,b],i)=>`<article class="ability-card"><span class="ability-number">0${i+1}</span><h3><span class="hover-word">${esc(a)}</span></h3><p>${b.split(/[·；]/).map(t=>`<span class="hover-word">${esc(t.trim())}</span>`).join('<span class="word-separator"> / </span>')}</p></article>`).join('');document.querySelectorAll('a[href^="tel:"]').forEach(a=>{a.href='tel:'+person.phone;if(a.closest('.footer-meta'))a.textContent=person.phone;});document.querySelector('.footer-meta>span').textContent=`${person.name} / ${person.city}`;
list.innerHTML=data.projects.map(p=>`<button class="work-item" data-id="${p.id}" aria-label="查看${p.title}${p.pending?'，作品待补充':''}">${p.cover?`<img src="${p.cover}" alt="" style="object-position:${p.position||'center'}" decoding="async">`:''}<div class="work-number"><span>(${p.number})</span><span class="work-arrow" aria-hidden="true">↗</span></div><div class="work-meta"><small>${p.en}</small><h3>${p.title}</h3><p>${p.short}</p></div></button>`).join('');
function gallery(images,posters=false){return `<div class="gallery${posters?' posters':''}">${images.map(([src,caption])=>`<figure><button class="image-button" data-image="${src}" data-caption="${esc(caption)}" aria-label="放大查看：${esc(caption)}"><img src="${src}" alt="${esc(caption)}" loading="lazy" decoding="async"></button><figcaption>${esc(caption)}</figcaption></figure>`).join('')}</div>`;}
function archiveCards(images){return `<div class="zhihu-archives">${images.map(([src,caption],i)=>`<article class="zhihu-archive"><h4><span>0${i+1} /</span> ${esc(caption.replace('截图',''))}</h4><button class="archive-image" data-image="${esc(src)}" data-caption="${esc(caption)}" aria-label="放大查看：${esc(caption)}"><img src="${esc(src)}" alt="${esc(caption)}" loading="lazy" decoding="async"></button><button class="archive-open" data-image="${esc(src)}" data-caption="${esc(caption)}" aria-label="查看${esc(caption)}大图">查看大图 <span aria-hidden="true">↗</span></button></article>`).join('')}</div>`;}
function xhsOverview(s){const [account,original]=s.images;return `<div class="xhs-overview"><article class="xhs-account"><h4><small>01 /</small> 账号档案</h4><button class="xhs-account-image" data-image="${esc(account[0])}" data-caption="${esc(account[1])}" aria-label="查看账号主页原图"><img src="${esc(account[0])}" alt="${esc(account[1])}" loading="lazy"></button><span class="xhs-hint">点击图片查看完整账号档案 ↗</span></article><article class="xhs-weekly"><h4><small>02 /</small> ${esc(s.weekly.title)}</h4><p class="xhs-weekly-intro">${esc(s.weekly.description)}</p><dl class="xhs-data-rows">${s.weekly.rows.map(([label,value,growth])=>`<div class="xhs-data-row"><dt>${esc(label)}</dt><dd class="xhs-data-value">${esc(value)}</dd><dd class="xhs-data-growth" aria-label="增长${esc(growth)}">${esc(growth)}</dd></div>`).join('')}</dl><div class="xhs-data-footer"><span>数据整理</span><button data-image="${esc(original[0])}" data-caption="${esc(original[1])}">查看原图 ↗</button></div></article></div>`;}
function xhsNotes(s){const tags=['内容呈现','持续发布','观察反馈'];return `<section class="project-section xhs-notes"><div class="xhs-notes-heading"><h3>${esc(s.title)}<span class="pink">.</span></h3><p>${esc(s.text)}</p></div><div class="xhs-notes-grid">${s.images.map(([src,caption],i)=>`<article class="xhs-note-card"><header><b>0${i+1}</b><span>${tags[i]}</span><i aria-hidden="true">↗</i></header><button class="xhs-note-image" data-image="${esc(src)}" data-caption="${esc(caption)}" aria-label="查看${esc(caption)}原图"><img src="${esc(src)}" alt="${esc(caption)}" loading="lazy" decoding="async"></button><div class="xhs-note-footer"><h4>${esc(caption)}</h4><button data-image="${esc(src)}" data-caption="${esc(caption)}" aria-label="查看${esc(caption)}原图">查看原图 ↗</button></div></article>`).join('')}</div></section>`;}
function process(items){return `<div class="process">${items.map(([title,text],i)=>`<article><small>0${i+1}</small><h4>${esc(title)}</h4><p>${esc(text)}</p></article>`).join('')}</div>`;}
function render(p){let body=`<p class="project-intro">${esc(p.intro)}</p>`;
if(p.metrics)body+=p.id==='zhihu'?`<div class="zhihu-metrics" role="group" aria-label="知乎运营成果">${p.metrics.map(([a,b])=>`<div class="zhihu-circle" tabindex="0" role="group" aria-label="${esc(b)}：${esc(a)}"><span class="zhihu-circle-label" aria-hidden="true">${esc(b)}</span><strong class="zhihu-circle-value" aria-hidden="true">${esc(a)}</strong></div>`).join('')}</div>`:`<div class="metrics">${p.metrics.map(([a,b])=>`<div class="metric"><b>${esc(a)}</b><span>${esc(b)}</span></div>`).join('')}</div>`;
if(p.note)body+=`<p class="source-note">${esc(p.note)}</p>`;
if(p.pending)body+='<section class="pending"><h3>作品待补充</h3><p>后续将在这里展示公众号文章、栏目策划与运营案例。</p></section>';
if(p.id==='ai'){body+=`<nav class="ai-nav" aria-label="AI 作品分类"><a href="#ai-posters" data-section="ai-posters">01 海报图片</a><a href="#ai-editorial" data-section="ai-editorial">02 AI 辅助创作图文</a><a href="#ai-games" data-section="ai-games">03 小游戏</a></nav><section id="ai-posters" aria-label="海报图片展廊"></section><section class="project-section"><h3>制作过程</h3>${process(p.process)}</section><section id="ai-editorial" class="project-section" aria-label="AI 辅助创作图文"></section><section id="ai-games" class="game-chapter" aria-label="小游戏：林间有龙"></section>`;}
else if(p.process)body+=`<section class="project-section"><h3>内容策划逻辑</h3>${process(p.process)}</section>`;
body+=p.sections.map((s,i)=>p.id==='xiaohongshu'&&i===1?xhsNotes(s):`<section class="project-section"><h3>${esc(s.title)}</h3><p>${esc(s.text)}</p>${p.id==='xiaohongshu'&&s.weekly?xhsOverview(s):p.id==='zhihu'&&i===0?archiveCards(s.images):p.id==='zhihu'&&i===1?gallery(s.images).replace('class="gallery"','class="gallery zhihu-audience"'):gallery(s.images)}</section>`).join('');
document.getElementById('project-label').textContent=p.en;document.getElementById('project-content').innerHTML=`<div class="project-cover">${p.cover?`<img src="${p.cover}" alt="${esc(p.title)}代表作品" style="object-position:${p.position||'center'}">`:'<img src="assets/silhouette.png" alt="抽象人物剪影">'}<div class="project-cover-title"><p>SELECTED WORK / ${p.number}</p><h2 id="project-title">${p.title}</h2></div></div><div class="project-body">${body}<button class="back-button end-back">返回作品目录 ↗</button></div>`;
}
let active=null,origin=null,savedY=0,busy=false,pendingHistory=false;
async function expandImage(p,rect,reverse=false){if(!p.cover||reduced.matches||window.motionState?.paused)return;const img=document.createElement('img');img.className='transition-image';img.src=p.cover;img.alt='';img.style.objectPosition=p.position||'center';const veil=document.createElement('div');veil.className='transition-veil';dialog.append(veil,img);const cover=dialog.querySelector('.project-cover').getBoundingClientRect();const target={left:cover.left,top:cover.top,width:cover.width,height:cover.height};const from=reverse?target:rect,to=reverse?rect:target;if(reverse){dialog.style.background='transparent';document.getElementById('project-content').style.visibility='hidden';dialog.querySelector('.project-toolbar').style.visibility='hidden';}const props=r=>({left:r.left+'px',top:r.top+'px',width:r.width+'px',height:r.height+'px'});Object.assign(img.style,props(from));veil.animate([{opacity:reverse?1:0},{opacity:reverse?0:1}],{duration:650,fill:'forwards'});try{await img.animate([props(from),props(to)],{duration:760,easing:'cubic-bezier(.22,1,.36,1)',fill:'forwards'}).finished;}finally{img.remove();veil.remove();}}
async function openProject(id,button,fromHistory=false){if(busy||active)return;let p=data.projects.find(p=>p.id===id);if(!p)return;busy=true;active=p;origin=button||list.querySelector(`[data-id="${id}"]`);savedY=scrollY;const rect=origin.getBoundingClientRect();origin.classList.add('is-opening');render(p);dialog.showModal();dialog.scrollTop=0;document.body.style.overflow='hidden';if(window.motionState)window.motionState.hidden=true;if(!fromHistory)history.pushState({project:id},'',`#project/${id}`);await expandImage(p,rect);document.getElementById('close-project').focus({preventScroll:true});busy=false;if(pendingHistory){pendingHistory=false;closeProject(true);}}
async function closeProject(fromHistory=false){if(busy||!active)return;busy=true;if(lightbox.open)lightbox.close();const p=active;dialog.scrollTop=0;await expandImage(p,origin.getBoundingClientRect(),true);dialog.close();dialog.style.background='';document.getElementById('project-content').style.visibility='';dialog.querySelector('.project-toolbar').style.visibility='';document.body.style.overflow='';if(window.motionState)window.motionState.hidden=false;window.scrollTo({top:savedY,behavior:'instant'});origin.classList.remove('is-opening');origin.focus({preventScroll:true});active=null;busy=false;if(!fromHistory&&history.state?.project)history.back();}
list.addEventListener('click',e=>{const b=e.target.closest('[data-id]');if(b)openProject(b.dataset.id,b);});
document.getElementById('close-project').addEventListener('click',()=>closeProject());dialog.addEventListener('cancel',e=>{e.preventDefault();closeProject();});
dialog.addEventListener('click',e=>{let b=e.target.closest('[data-image]');if(b){lightbox.querySelector('img').src=b.dataset.image;lightbox.querySelector('img').alt=b.dataset.caption;lightbox.querySelector('p').textContent=b.dataset.caption;if(b.closest('.zhihu-archives,.xhs-overview,.xhs-notes')){const top=dialog.scrollTop;lightbox.addEventListener('close',()=>{if(dialog.open){b.focus({preventScroll:true});dialog.scrollTop=top;}},{once:true});}lightbox.showModal();return;}let a=e.target.closest('[data-section]');if(a){e.preventDefault();dialog.querySelector('#'+a.dataset.section).scrollIntoView({behavior:reduced.matches?'instant':'smooth',block:'start'});}if(e.target.closest('.end-back'))closeProject();});
document.getElementById('close-lightbox').addEventListener('click',()=>lightbox.close());lightbox.addEventListener('click',e=>{if(e.target===lightbox)lightbox.close();});
window.addEventListener('popstate',()=>{const id=location.hash.match(/^#project\/(.+)$/)?.[1];if(!id&&active){if(busy)pendingHistory=true;else closeProject(true);}else if(id&&!active)openProject(id,null,true);});
const deep=location.hash.match(/^#project\/(.+)$/)?.[1];if(deep&&data.projects.some(p=>p.id===deep)){history.replaceState(null,'','#work');document.getElementById('work').scrollIntoView({behavior:'instant'});openProject(deep);}
const toggle=document.querySelector('.motion-toggle');function motionUI(){const paused=window.motionState?.paused??reduced.matches;toggle.setAttribute('aria-pressed',String(paused));toggle.setAttribute('aria-label',paused?'恢复动态效果':'暂停动态效果');toggle.innerHTML=`${paused?'静态':'动态'} <span>${paused?'▶':'Ⅱ'}</span>`;}toggle.addEventListener('click',()=>{if(window.motionState)window.motionState.paused=!window.motionState.paused;motionUI();});reduced.addEventListener('change',e=>{if(window.motionState)window.motionState.paused=e.matches;motionUI();});motionUI();
const cursor=document.querySelector('.cursor-label');list.addEventListener('pointermove',e=>{if(e.pointerType==='touch')return;cursor.style.transform=`translate(${e.clientX-35}px,${e.clientY-35}px)`;cursor.style.opacity='1';const b=e.target.closest('[data-id]');cursor.textContent=b?.dataset.id==='wechat'?'SOON':'VIEW';if(b?.querySelector('img')&&!reduced.matches){const r=b.getBoundingClientRect();b.querySelector('img').style.transform=`scale(1.04) translate(${(e.clientX-r.left-r.width/2)*.016}px,${(e.clientY-r.top-r.height/2)*.016}px)`;}});list.addEventListener('pointerleave',()=>{cursor.style.opacity='0';list.querySelectorAll('img').forEach(i=>i.style.transform='');});list.addEventListener('pointerout',e=>{const b=e.target.closest('[data-id]');if(b&&!b.contains(e.relatedTarget)&&b.querySelector('img'))b.querySelector('img').style.transform='';});list.addEventListener('click',()=>cursor.style.opacity='0');
let ticking=false;function scrollEffects(){ticking=false;const about=document.getElementById('about').getBoundingClientRect(),work=document.getElementById('work').getBoundingClientRect(),h=innerHeight;const title=document.querySelector('.hero-title');if(!reduced.matches){title.style.transform=`translateY(${-Math.min(scrollY,h)*.17}px)`;title.style.opacity=String(Math.max(0,1-scrollY/(h*.8)));}else{title.style.transform='none';title.style.opacity='1';}document.getElementById('about').classList.toggle('about-active',about.top<h*.5&&about.bottom>h*.25);const progress=Math.max(0,Math.min(1,(h-work.top)/(h*.6)));list.querySelectorAll('.work-item').forEach((item,i)=>{const q=reduced.matches?1:Math.max(0,Math.min(1,progress*1.3-i*.09));item.style.transform=`translateY(${(1-q)*45}px)`;item.style.opacity=String(q);});if(document.querySelector('.visual-stage.no-webgl')){const paper=Math.max(0,Math.min(1,(h*.85-about.top)/(h*.7)))*(1-Math.max(0,Math.min(1,(h*.75-work.top)/(h*.65))));document.querySelector('.visual-stage').style.background=paper>.5?'#efeee9':'#080808';document.querySelector('.visual-fallback').style.filter=paper>.5?'invert(1)':'none';}document.getElementById('chapter').textContent=work.top<h*.5?'03':about.top<h*.5?'02':'01';}
window.addEventListener('scroll',()=>{if(!ticking){ticking=true;requestAnimationFrame(scrollEffects);}},{passive:true});window.addEventListener('resize',scrollEffects);scrollEffects();
})();
