/* 所有作品文字、数据与素材路径在此集中维护。图片原件来自用户提供的 PPT。 */
window.PORTFOLIO={
 person:{name:'乔国康',englishName:'QIAOGUOKANG',education:'硕士',city:'上海 / 杭州',role:'内容运营',phone:'13258117435',intro:'关注人文与情感内容，连接用户兴趣与表达。',description:'从选题、文案到发布与复盘，也用 AI 探索视觉创作。',skills:[['内容运营','热点追踪 · 选题策划 · 标题与文案'],['平台与数据','知乎 · 小红书 · 公众号；浏览 · 点赞 · 收藏 · 互动率 · 转化率复盘'],['视觉与 AI','即梦 · Canva · 醒图 · 剪映 · ChatGPT · Codex']]},
 projects:[
 {id:'zhihu',number:'01',title:'知乎账号运营',en:'ZHIHU / OPERATIONS',short:'从零搭建 · 人文与情感',cover:'assets/s8-image38.png',position:'center',intro:'从零搭建知乎账号，围绕人文与情感内容持续发布回答。',metrics:[['50+','累计发布回答'],['550+','三个月内粉丝增长'],['100万+','单篇最高浏览量']],sections:[
 {title:'账号与运营数据',text:'账号主页及后台数据保留原始截图，便于查看具体指标与记录。',images:[['assets/s8-image38.png','账号主页'],['assets/s8-image39.png','作品数据截图'],['assets/s8-image40.png','互动数据截图']]},
 {title:'理解内容的阅读者',text:'用户以女性为主，占比 88.5%，男性占比 11.5%。兴趣集中在人文、情感、两性关系，广东、山东、河南用户最多。',images:[['assets/s9-image45.png','性别与年龄分布'],['assets/s9-image44.png','兴趣与地域分布']]}
 ]},
 {id:'xiaohongshu',number:'02',title:'小红书账号运营',en:'XIAOHONGSHU / CONTENT',short:'选题包装 · 图文内容 · 复盘',cover:'assets/s11-image54.png',position:'center',intro:'面向年轻读者的情感类网络小说推荐账号。以图文为主，偶尔发布视频，每周更新 4—5 次。',metrics:[['4–5','每周更新次数'],['4.3万+','单篇最高浏览量'],['4000+','点赞收藏']],process:[['用户洞察','识别目标用户的内容偏好、痛点与情绪触发点。'],['选题包装','把内容价值转化为具体场景，设计标题与首图。'],['内容发布','优化开篇节奏、信息密度与互动引导。'],['数据复盘','对比浏览、互动与转化表现，沉淀可复用规律。']],sections:[
 {weekly:{title:'近7日数据',description:'笔记涨粉和观看增长明显',rows:[['观看','3.6万','+150%'],['互动数','6556','+516%'],['新增粉丝','82','+74%'],['主页访客','1200','+40%']]},title:'账号与内容',text:'内容从读者兴趣出发，通过标题、首图和开篇节奏呈现小说的情绪与场景。',images:[['assets/s5-image28.png','个人账号：文不如故'],['assets/xhs-seven-days-original.png','近7日数据整理原图']]},
 {title:'笔记发布与复盘',text:'保留笔记列表与后台截图。不同截图的统计周期和指标分别以图中标注为准。',images:[['assets/s6-image32.png','笔记列表与封面'],['assets/s6-image33.png','系列笔记发布记录'],['assets/s6-image34.png','笔记数据复盘']]}
 ]},
 {editorial:{"title": "AI 辅助创作图文", "intro": "围绕留学生求职主题，探索 AI 辅助下的图文表达。", "items": [{"src": "assets/ai-content-1.png", "thumb": "assets/ai-content-1-thumb.jpg", "title": "留学生秋招求职辅导", "width": 628, "height": 837}, {"src": "assets/ai-content-2.png", "thumb": "assets/ai-content-2-thumb.jpg", "title": "留学生求职规划", "width": 1024, "height": 1360}, {"src": "assets/ai-content-3.png", "thumb": "assets/ai-content-3-thumb.jpg", "title": "留学生远程实习", "width": 1024, "height": 1360}, {"src": "assets/ai-content-4.png", "thumb": "assets/ai-content-4-thumb.jpg", "title": "金融留学生实习规划", "width": 358, "height": 478}, {"src": "assets/ai-content-5.png", "thumb": "assets/ai-content-5-thumb.jpg", "title": "助力留学生上岸名企", "width": 1376, "height": 1840}, {"src": "assets/ai-content-6.png", "thumb": "assets/ai-content-6-thumb.jpg", "title": "留学生四大远程实习", "width": 1086, "height": 1448}, {"src": "assets/ai-content-7.png", "thumb": "assets/ai-content-7-thumb.jpg", "title": "留学生回国求职", "width": 1088, "height": 1445}]},id:'ai',number:'03',title:'AI 制作',en:'AI / CREATIVE PRACTICE',short:'海报图片 · 小游戏',cover:'assets/s11-image53.png',position:'center',intro:'为小说推文自媒体账号及高顿留学生求职官方账号，制作具有独立出版气质/广告投放风格的海报及图文，并持续探索AI辅助下的视觉表达。',posters:[["assets/poster-added-1.png", "非天夜翔作品阅读榜"], ["assets/poster-added-2.png", "丰饶之海"], ["assets/poster-added-3.png", "刑侦文必吃榜"], ["assets/poster-added-4.png", "过期的初恋与非人之恋 · 阅读感受"], ["assets/poster-added-5.jpg", "古早民国文书单"],['assets/s11-image51.png','彼得潘与辛德瑞拉'],['assets/s11-image52.png','假面的告白'],['assets/s11-image53.png','苹果冒险'],['assets/s11-image54.png','判官'],['assets/s11-image48.png','龙族 3 · 黑月之潮']],process:[['提炼关键词','从内容主题与情绪中提炼视觉关键词。'],['搭建 Prompt','将关键词转化为构图、字体与色彩要求。'],['筛选与调整','筛选初稿，调整构图、文字和留白。'],['输出视觉','保留文学性与视觉辨识度，输出社媒封面。']],demo:{video:'assets/game-recording.mp4',poster:'assets/game-poster.jpg',name:'林间有龙',intro:'一次将 AI 创作与互动体验结合的小游戏实践。',url:'https://qiaoguokang.github.io/ai-demo-page/',title:'体验《林间有龙》',description:'林间有龙 · 一段同行的旅程。穿过森林，和小黑龙一起长大。支持上划跳跃、下划滑行及呼唤小龙；键盘可使用 ↑ / ↓ / F。'},sections:[]}
 ]
};
