/* Inline chapter within the AI project scroll container. */
(()=>{'use strict';const dialog=document.querySelector('#project-dialog'),content=document.querySelector('#project-content'),game=PORTFOLIO.projects.find(p=>p.id==='ai').demo,reduce=matchMedia('(prefers-reduced-motion: reduce)');let cleanup=()=>{};
function mount(){cleanup();const section=content.querySelector('#ai-games');if(!section)return;
section.innerHTML=`<video class="game-video" playsinline muted preload="none"></video><div class="game-shade" aria-hidden="true"></div><div class="game-caption"><p>AI 制作 / 小游戏</p><h3></h3><p class="game-description"></p><a target="_blank" rel="noopener noreferrer">体验游戏 ↗</a></div><button class="game-start">播放录屏 ▶</button><p class="game-status" role="status"></p><div class="game-controls" aria-label="视频播放控制"><button data-play>播放</button><output>0:00 / 1:30</output><input type="range" min="0" max="100" step="0.1" value="0" aria-label="播放进度"><button data-mute aria-pressed="true">声音：关</button><button data-full>全屏 ↗</button></div>`;
const video=section.querySelector('video'),play=section.querySelector('[data-play]'),mute=section.querySelector('[data-mute]'),start=section.querySelector('.game-start'),status=section.querySelector('.game-status'),seek=section.querySelector('input'),time=section.querySelector('output');video.poster=game.poster;video.muted=true;section.querySelector('h3').textContent=game.name;section.querySelector('.game-description').textContent=game.intro;section.querySelector('a').href=game.url;
let visible=false,disposed=false;const fmt=t=>`${Math.floor((t||0)/60)}:${String(Math.floor((t||0)%60)).padStart(2,'0')}`;
function ui(){play.textContent=video.paused?'播放':'暂停';play.setAttribute('aria-label',play.textContent+'录屏');mute.textContent=video.muted?'声音：关':'声音：开';mute.setAttribute('aria-pressed',String(video.muted));mute.setAttribute('aria-label',video.muted?'开启声音':'关闭声音');start.hidden=!video.paused||video.currentTime>0;}
async function run(){if(disposed)return;if(!video.getAttribute('src')){video.src=game.video;video.load();}try{await video.play();if(!visible||!dialog.open||disposed)video.pause();}catch(e){if(e.name!=='AbortError'){status.textContent='点击播放，观看游戏实录';start.hidden=false;}}}
function sync(){const r=section.getBoundingClientRect(),h=dialog.clientHeight;const next=dialog.open&&!document.hidden&&(document.fullscreenElement===section||Math.max(0,Math.min(r.bottom,h)-Math.max(0,r.top))>=Math.min(r.height,h)*.55);dialog.classList.toggle('game-in-view',next);if(next!==visible){visible=next;section.classList.toggle('is-visible',next);if(!next)video.pause();else if(!reduce.matches)run();}if(!dialog.open)video.pause();}
play.onclick=()=>video.paused?run():video.pause();start.onclick=()=>play.click();mute.onclick=()=>{video.muted=!video.muted;ui();};seek.oninput=()=>{if(Number.isFinite(video.duration))video.currentTime=Number(seek.value)/100*video.duration;};
['play','pause','ended','volumechange'].forEach(e=>video.addEventListener(e,ui));video.ontimeupdate=()=>{seek.value=video.duration?video.currentTime/video.duration*100:0;time.textContent=`${fmt(video.currentTime)} / ${fmt(video.duration)}`;seek.setAttribute('aria-valuetext',time.textContent);};video.onwaiting=()=>status.textContent='正在加载录屏…';video.onplaying=video.oncanplay=()=>status.textContent='';video.onerror=()=>{status.textContent='录屏暂时无法加载，仍可点击「体验游戏」。';start.hidden=true;};
section.querySelector('[data-full]').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if(section.requestFullscreen)await section.requestFullscreen();else if(video.webkitEnterFullscreen)video.webkitEnterFullscreen();}catch{status.textContent='当前浏览器暂时无法进入全屏。';}};
function size(){section.style.setProperty('--game-width',dialog.clientWidth+'px');sync();}const ro=new ResizeObserver(size);ro.observe(dialog);const mo=new MutationObserver(sync);mo.observe(dialog,{attributes:true,attributeFilter:['open']});dialog.addEventListener('scroll',sync,{passive:true});document.addEventListener('visibilitychange',sync);document.addEventListener('fullscreenchange',sync);const reduced=()=>{if(reduce.matches)video.pause();};reduce.addEventListener('change',reduced);ui();size();
cleanup=()=>{disposed=true;video.pause();ro.disconnect();mo.disconnect();dialog.removeEventListener('scroll',sync);document.removeEventListener('visibilitychange',sync);document.removeEventListener('fullscreenchange',sync);reduce.removeEventListener('change',reduced);dialog.classList.remove('game-in-view');};}
new MutationObserver(mount).observe(content,{childList:true});if(content.querySelector('#ai-games'))mount();
if(location.hash==='#project/ai/game'){history.replaceState(null,'','#work');document.querySelector('[data-id="ai"]').click();setTimeout(()=>content.querySelector('#ai-games')?.scrollIntoView({behavior:'instant'}),900);}
})();
