(()=>{'use strict';const parent=document.querySelector('#project-dialog'),content=document.querySelector('#project-content'),items=PORTFOLIO.projects.find(p=>p.id==='ai').posters,reduce=matchMedia('(prefers-reduced-motion: reduce)');const thumb=s=>s.replace(/\.[^.]+$/,'-thumb.jpg');let dispose=()=>{};
function mount(){dispose();const stage=content.querySelector('#ai-posters');if(!stage)return;stage.innerHTML=`<div class="poster-orbit"></div><div class="poster-copy"><small>AI / VISUAL CREATION</small><h3>以文字为起点<br>让内容拥有视觉表达</h3><p>海报、书单与阅读视觉，记录内容策划与 AI 辅助创作的实践。</p><button class="poster-all">浏览全部 10 张 ↗</button><div class="poster-notes"><div><b>内容提炼</b><span>从主题与阅读感受出发</span></div><div><b>视觉编排</b><span>探索字体、色彩与构图</span></div><div><b>AI 辅助</b><span>结合生成、筛选与调整</span></div></div></div><button class="orbit-pause" aria-pressed="false">暂停旋转 Ⅱ</button>`;
const orbit=stage.querySelector('.poster-orbit'),toggle=stage.querySelector('.orbit-pause');const cards=items.map(([src,title],i)=>{const n=document.createElement('button');n.className='orbit-card';n.setAttribute('aria-label','查看：'+title);const img=new Image();img.src=thumb(src);img.alt=title;const face=document.createElement('span');face.className='orbit-face';face.append(img);n.append(face);orbit.append(n);n.onclick=()=>open(i,n);return n;});
const viewer=document.createElement('dialog');viewer.className='poster-viewer';viewer.setAttribute('aria-label','海报作品查看器');viewer.innerHTML=`<header><button data-prev aria-label="上一张">←</button><span class="poster-count"></span><button data-next aria-label="下一张">→</button><button data-zoom>放大阅读</button><button data-close>关闭 ×</button></header><div class="poster-scroll"><img alt=""></div><nav class="poster-index" aria-label="选择海报"></nav>`;document.body.append(viewer);const image=viewer.querySelector('.poster-scroll img'),scroll=viewer.querySelector('.poster-scroll');let index=0,origin=null,zoom=false;
items.forEach(([src,title],i)=>{const btn=document.createElement('button');btn.setAttribute('aria-label',`第 ${i+1} 张：${title}`);const im=new Image();im.src=thumb(src);im.alt='';im.loading='lazy';btn.append(im);btn.onclick=()=>show(i);viewer.querySelector('nav').append(btn);});
function show(i){index=(i+items.length)%items.length;zoom=false;scroll.classList.remove('zoomed');viewer.querySelector('[data-zoom]').textContent='放大阅读';image.src=items[index][0];image.alt=items[index][1];viewer.querySelector('.poster-count').textContent=`${String(index+1).padStart(2,'0')} / 10 · ${items[index][1]}`;viewer.querySelectorAll('nav button').forEach((b,j)=>b.setAttribute('aria-current',String(j===index)));scroll.scrollTo(0,0);}
function open(i,el){origin=el;show(i);viewer.showModal();viewer.querySelector('[data-close]').focus();}function close(){viewer.close();origin?.focus({preventScroll:true});}
viewer.querySelector('[data-close]').onclick=close;viewer.addEventListener('cancel',e=>{e.preventDefault();close();});viewer.querySelector('[data-prev]').onclick=()=>show(index-1);viewer.querySelector('[data-next]').onclick=()=>show(index+1);viewer.addEventListener('keydown',e=>{if(e.key==='ArrowRight'){e.preventDefault();show(index+1);}if(e.key==='ArrowLeft'){e.preventDefault();show(index-1);}});viewer.querySelector('[data-zoom]').onclick=()=>{zoom=!zoom;scroll.classList.toggle('zoomed',zoom);viewer.querySelector('[data-zoom]').textContent=zoom?'适合窗口':'放大阅读';};
// Native scrolling supports touch and trackpads; mouse drag pans the enlarged original.
let drag=null;scroll.onpointerdown=e=>{if(!zoom||e.pointerType!=='mouse')return;drag=[e.clientX,e.clientY,scroll.scrollLeft,scroll.scrollTop];scroll.setPointerCapture(e.pointerId);e.preventDefault();};scroll.onpointermove=e=>{if(drag){scroll.scrollLeft=drag[2]-e.clientX+drag[0];scroll.scrollTop=drag[3]-e.clientY+drag[1];}};scroll.onpointerup=scroll.onpointercancel=()=>drag=null;image.draggable=false;
stage.querySelector('.poster-all').onclick=e=>open(0,e.currentTarget);
// Geometry measured against the 1179 x 864 reference: clipping line y=694.
const geometry={referenceWidth:1179,stageHeight:694,centerY:680,radius:390,cardHeight:148,arc:224,seconds:75};
let angle=0,last=0,speed=0,paused=reduce.matches,visible=false,raf=0,hover=false,width=0,cx=0,cy=0,radius=0,cardHeight=0,stageHeight=0,hoverUntil=0;
function label(){toggle.textContent=paused?'继续旋转 ▶':'暂停旋转 Ⅱ';toggle.setAttribute('aria-pressed',String(paused));}toggle.onclick=()=>{paused=!paused;label();};label();
cards.forEach(card=>{card.onpointerenter=e=>{if(e.pointerType==='mouse'){hover=true;speed=0;hoverUntil=Infinity;}};card.onpointerleave=()=>{hover=false;hoverUntil=performance.now()+150;};});
function paint(){cards.forEach((card,i)=>{const u=((angle/(Math.PI*2)+(i+.5)/10)%1+1)%1,a=(-geometry.arc/2+u*geometry.arc)*Math.PI/180,x=cx+Math.sin(a)*radius,y=cy-Math.cos(a)*radius;card.style.transform=`translate3d(${x}px,${y}px,0) translate(-50%,-50%)`;card.firstElementChild.style.transform=`rotate(${a*180/Math.PI*.82}deg)`;card.tabIndex=y-cardHeight*.7>stageHeight?-1:0;});}
function layout(){const next=parent.clientWidth;if(next===width)return;width=next;const mobile=width<700,scale=mobile?Math.max(.65,width/geometry.referenceWidth):width/geometry.referenceWidth;cx=width/2;cy=mobile?580:geometry.centerY*scale;radius=mobile?340:geometry.radius*scale;cardHeight=mobile?100:geometry.cardHeight*scale;stageHeight=mobile?620:geometry.stageHeight*scale;stage.style.setProperty('--orbit-width',width+'px');stage.style.setProperty('--stage-height',stageHeight+'px');stage.style.setProperty('--poster-height',cardHeight+'px');stage.style.setProperty('--copy-top',(mobile?330:444*scale)+'px');cards.forEach(card=>{const img=card.querySelector('img');const ratio=img.naturalWidth&&img.naturalHeight?img.naturalWidth/img.naturalHeight:.74;card.style.width=cardHeight*ratio+'px';card.style.height=cardHeight+'px';});paint();}
cards.forEach(card=>card.querySelector('img').addEventListener('load',()=>{const img=card.querySelector('img');card.style.width=cardHeight*img.naturalWidth/img.naturalHeight+'px';}));
function tick(now){const dt=Math.min((now-last)/1000||0,.05);last=now;const stop=paused||reduce.matches||hover||now<hoverUntil||stage.contains(document.activeElement)||viewer.open||!visible||!parent.open||document.hidden;speed+=(Number(!stop)-speed)*(1-Math.exp(-dt*12));if(speed>.001&&!document.hidden&&visible&&parent.open){angle=(angle+dt*speed*Math.PI*2/geometry.seconds)%(Math.PI*2);paint();}raf=requestAnimationFrame(tick);}
const io=new IntersectionObserver(e=>visible=e[0].isIntersecting,{root:parent,threshold:0});io.observe(stage);const ro=new ResizeObserver(layout);ro.observe(parent);const mo=new MutationObserver(()=>{if(!parent.open&&viewer.open)close();});mo.observe(parent,{attributes:true,attributeFilter:['open']});const reduced=()=>{paused=reduce.matches;label();};reduce.addEventListener('change',reduced);layout();raf=requestAnimationFrame(tick);dispose=()=>{cancelAnimationFrame(raf);io.disconnect();ro.disconnect();mo.disconnect();reduce.removeEventListener('change',reduced);viewer.remove();};}
new MutationObserver(mount).observe(content,{childList:true});mount();})();




